version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
  dash:
    build:
      context: ./
      dockerfile: Dockerfile1
    depends_on:
      - api
    restart: always
